### ISSUE TITLE
error about ev_city

### ISSUE THREAD

**Issue by seonjin13** [StavrosOrf/EV2Gym#12]
I'm currently working on a project using the ev2gym package and encountered an issue when trying to run my script. 
The error message indicates that the module ev2gym.ev_city is missing.

[train_stable_baselines.py : 61 lines code]
gym.envs.register(id='evs-v0', entry_point='ev2gym.ev_city:ev2gym',

Here's the code I'd met the error.
I've checked the ev2gym package installation and the expected directory structure, but the ev_city module doesn't seem to be present.
I also couldn't find any reference to ev_city in the package's GitHub repository.

Despite these efforts, I haven't been able to resolve the issue. 

Thank you for your help!

**Comment by StavrosOrf** [comment]
Hello, there is an error indeed in this script. The newer version registers the environment with entry point:

```    
gym.envs.register(id='evs-v0', entry_point='ev2gym.models.ev2gym_env:EV2Gym',
                      kwargs={'config_file': config_file,
                              'reward_function': reward_function,
                              'state_function': state_function,
                              })
```
