### ISSUE TITLE
help

### ISSUE THREAD

**Issue by lqhdehub** [StavrosOrf/EV2Gym#17]
Hello, author:
This open source code of yours does not seem to be particularly studious, as it is more like an integrated third-party library, what would you recommend for beginners?
Looking forward to your reply.

**Comment by StavrosOrf** [comment]
Hello, thank you for raising this issue.

We have created a nice introductory Jupyter notebook where you can get an idea of how the simulator works and how to apply Reinforcement Learning with EV2Gym (https://github.com/StavrosOrf/EV2Gym/blob/main/tutorials/CreateYourCustomRLAlgorithm.ipynb).

Furthermore, I suggest you check the EV2Gym paper to get a better understanding of all the mathematical models used in the simulator. The paper is available for free at ArXiv (https://arxiv.org/abs/2404.01849), now also published at IEEE Transactions on Intelligent Transportation (https://ieeexplore.ieee.org/document/10803908).

Last but not least, I suggest you take a look at the README file which has a short guide on getting started. Also, try to run the example.py file and get some outputs (https://github.com/StavrosOrf/EV2Gym/blob/main/example.py)

**Comment by lqhdehub** [comment]
Thank you very much for your reply

I wonder if it is convenient for you to add a requirements.txt file so that we can easily install the libraries that the project depends on.

**Comment by StavrosOrf** [comment]
This is indeed a nice suggestion! I added a requirements.txt file for the EV2Gym dependencies. Note that, for libraries not included in requirements.txt but are needed you can update the latest version. For example, stable-baselines3.
